### ISSUE TITLE
Can't connect to Google home addon - Could not get master token.

### ISSUE THREAD

**Issue by mitch55500** [leikoilja/ha-google-home#528]
Hello, 

I have read the other issues with the same error than mine, but I couldn't resolve it.

I use the Google Home addon of Home Assistant, but the connection is refused. 
I've tried to take off the protection methods to my google account too.

Here the log : 

`2022-05-13 10:58:25 DEBUG (MainThread) [glocaltokens.client] Initializing new GLocalAuthenticationTokens instance.
2022-05-13 10:58:25 DEBUG (MainThread) [glocaltokens.client] Set GLocalAuthenticationTokens client access_token, homegraph, access_token_date and homegraph_date to None
2022-05-13 10:58:25 DEBUG (MainThread) [glocaltokens.client] Set GLocalAuthenticationTokens client username to "m*******************", password to "V********", master_token to "" and android_id to 
2022-05-13 10:58:25 DEBUG (SyncWorker_15) [glocaltokens.client] There is no stored master_token, logging in using username and password
2022-05-13 10:58:25 DEBUG (SyncWorker_15) [glocaltokens.client] There is no stored android_id, generating a new one
2022-05-13 10:58:25 DEBUG (SyncWorker_15) [glocaltokens.client] Generating android id...
2022-05-13 10:58:25 DEBUG (SyncWorker_15) [glocaltokens.client] Generated android id: 02d89392d5f67400
2022-05-13 10:58:25 ERROR (SyncWorker_15) [glocaltokens.client] [!] Could not get master token.
2022-05-13 10:58:25 DEBUG (SyncWorker_15) [glocaltokens.client] Request response: {'Error': 'NeedsBrowser', 'Url': 'https://accounts.google.com/signin/continue?sarp=1&scc=1&continue=https://accounts.google.com/o/android/IDELETEDTHIS', 'ErrorDetail': 'To access your account, you must sign in on the web. Touch Next to start browser sign-in.'}
2022-05-13 10:58:25 ERROR (MainThread) [custom_components.google_home] `

*Edit : Of course, no pop-up opens.

**Comment by tomaspre** [comment]
+1
I have the exact same problem. Some of my newly added devices would not show up so I removed and re-added the integration and now I can't even log in. Running the latest version from HACS (v1.9.10).

`2022-05-14 14:35:43 DEBUG (MainThread) [glocaltokens.client] Initializing new GLocalAuthenticationTokens instance.
2022-05-14 14:35:43 DEBUG (MainThread) [glocaltokens.client] Set GLocalAuthenticationTokens client access_token, homegraph, access_token_date and homegraph_date to None
2022-05-14 14:35:43 DEBUG (MainThread) [glocaltokens.client] Set GLocalAuthenticationTokens client username to "p********************", password to "u***************", master_token to "" and android_id to 
2022-05-14 14:35:43 DEBUG (SyncWorker_1) [glocaltokens.client] There is no stored master_token, logging in using username and password
2022-05-14 14:35:43 DEBUG (SyncWorker_1) [glocaltokens.client] There is no stored android_id, generating a new one
2022-05-14 14:35:43 DEBUG (SyncWorker_1) [glocaltokens.client] Generating android id...
2022-05-14 14:35:43 DEBUG (SyncWorker_1) [glocaltokens.client] Generated android id: 6f4f8588271368c7
2022-05-14 14:35:43 ERROR (SyncWorker_1) [glocaltokens.client] [!] Could not get master token.
2022-05-14 14:35:43 DEBUG (SyncWorker_1) [glocaltokens.client] Request response: {'Error': 'NeedsBrowser', 'Url': 'https://accounts.google.com/signin/continue?sarp=1&scc=1&continue=https://accounts.google.com/o/android/auth?hl%3Den_us%26xoauth_display_name%3DAndroid%2BLogin%2BService%26source%3DAndroid%2BLogin&plt=CENSORED', 'ErrorDetail': 'To access your account, you must sign in on the web. Touch Next to start browser sign-in.'}
2022-05-14 14:35:43 ERROR (MainThread) [custom_components.google_home] `

**Comment by mitch55500** [comment]
I had the same problem and I did the same thing than you (removed and re-added).
On 2022.5.4 version of HA.

**Comment by Wurmie1978** [comment]
Sadly I have the same problem. Reinstalled the whole of my home assistant and as first addon I installed HACS and this one. Still i get this error..

**Comment by Eagle99Eye** [comment]
I have the same issue (HA 2022.5.4 - addon 1.9.10). Did clean install of all components - nothing helped

**Comment by TheLinthus** [comment]
Having this problem also. Already tried a lot of thigs found here, nothing seems to work.

**Comment by KapJI** [comment]
I guess this is related https://github.com/simon-weber/gpsoauth/issues/37

**Comment by Mylezz** [comment]
Same Issue here!
![image](https://user-images.githubusercontent.com/23045776/168698733-0d594922-f014-4664-8738-b781b0e3880b.png)

**Comment by Dendrowen** [comment]
Same issue. Tried reinstalling, but didn't work.
Home Assistant Core 2022.5.4
Home Assistant Supervisor 2022.05.2
Home Assistant OS 8.0
Kernel version 5.15.32-v7
Agent version 1.2.1
HACS 1.24.5
Google home integration 1.9.10

**Comment by Deathbot64** [comment]
same error with a fresh HA install. Tried removing 2FA but even then same error

**Comment by sk8er000** [comment]
same here my timers and alarms sensors suddenly stopped working. I decided to delete and reinstall the extension and now I'm unable to even login no matter if I use 2FA or not. I tried different google accounts too

**Comment by ArnyminerZ** [comment]
This seems quite worrying, pretty sure it has to do with some Google Api change. Further investigation shall be performed.

**Comment by ArnyminerZ** [comment]
This is related to `glocaltokens`, so the issue is moved there. See leikoilja/glocaltokens#245

**Comment by leikoilja** [comment]
Fixed in `ha-google-home` v1.9.11 🚀
https://github.com/leikoilja/ha-google-home/releases/tag/v1.9.11

Please update to the latest version and verify it checks :)

**Comment by hugalafutro** [comment]
I just updated to 1.9.11, restarted HA, created new app password for my gmail address, tried to log in with it into integration and still get `[!] Could not get master token.`. Is there something more I need to do? Thanks!

**Comment by leikoilja** [comment]
Reopening this issue, since it seems to be on `ha-google-home` now. 
The authentication issue we first saw was [fixed and tested](https://github.com/leikoilja/glocaltokens/issues/245) in `glocaltoken` using python SDK and it's provided example code. 

Since we still keep seeing the same issue in Home Assistant, let's try to dig deeper here to understand what's an issue. Supposedly it's to do with dependencies during installation, but we look into it deeper.

**Comment by Pronown** [comment]
> @mitch55500, @hugalafutro, @Pronown, @srappan, @dineshkathir, @Neolanco, can one of you please double-check `glocaltokens` version installed in your HA instance? I am assuming that it might not have been automatically pulled and installed when updating `ha-google-home`. You would need to ssh to your container/server and do smth like `pip freeze` to see? 

I am available now to ssh. Still fairly new to Linux and how the file hierchy works, but if you tell me commands, I can input them.

**Comment by hugalafutro** [comment]
I run latest ha in docker, here's the output from inside the container: https://o.o5.ddns.net/z3KcF I will now bring the stack down and rebuild, but it'll take time on pi. Will report if that changes anything.

**Comment by leikoilja** [comment]
uuu, it's highly dependant on what HA installation you have done, @Pronown. If it was using docker container you should be able to just run a command like this:
`docker exec -it homeassistant pip freeze | grep glocaltokens` 
if some other option, check this [article](https://developers.home-assistant.io/docs/operating-system/debugging/).

@hugalafutro, thank you for the update. Seems like my assumption was right, you have `glocaltokens==0.6.3`, when the latest (with the fix) is `glocaltokens==0.6.4`. I think we need to specify the `glocaltokens` version to be min `0.6.4` in this package. @KapJI, what do you think?

**Comment by mitch55500** [comment]
On my HA, glocaltokens==0.6.3

**Comment by leikoilja** [comment]
that's the issue. flip i think it's my fault, I keep forgetting updating the `manifest` file with a version requirement :D

**Comment by leikoilja** [comment]
that's the issue. flip i think it's my fault, I keep forgetting updating the `manifest` file with a version requirement :D

**Comment by srappan** [comment]
custom_components/google_home/manifest.json
Yep missed change

**Comment by leikoilja** [comment]
Sorry, guys, my fault (not the first time 😮‍💨 🤦 😅 )
Fixed here: https://github.com/leikoilja/ha-google-home/pull/541
will merge and deploy a new release

**Comment by Pronown** [comment]
Haha, looks like we got it figured out before I could put the commands in. Thanks for all your work!
________________________________

**Comment by hugalafutro** [comment]
@Neolanco just wait a bit till new version is pushed out, update via hacs and it will do the work automatically

**Comment by leikoilja** [comment]
Okay, new patch release is out, it should fix it.
[v1.9.12](https://github.com/leikoilja/ha-google-home/releases/tag/v1.9.12)
Please update and verify all good 🚀 🔥

**Comment by mitch55500** [comment]
@leikoilja, the same error for me too. It doesn't work.

**Comment by hugalafutro** [comment]
strange, it works here, I created a timer to test and could see it in ha

**Comment by leikoilja** [comment]
hmm, @mitch55500 & @Pronown, can you guys please dig deeper into your container/ha environment to see which version `glocaltokens` is for you now (see some instruction [here](https://github.com/leikoilja/ha-google-home/issues/528#issuecomment-1143435398))?

**Comment by Pronown** [comment]
> @leikoilja, the same error for me too. It doesn't work.

Bro! Reinstall from HACS and restart just fixed mine!

**Comment by Pronown** [comment]
@leikoilja do you want me to check that still, now that it worked?

**Comment by leikoilja** [comment]
No, no worries, thank you, @Pronown. Happy to hear it has eventually worked for you :)

**Comment by aaronpowell** [comment]
I've just come across this add-on and am trying to set it up but am hitting this error.

Been through the trouble shooting guides as listed, installed from HACS/uninstalled/reinstalled. I've also tried enabling and disabling 2FA (using App Password when having 2FA setup), still no luck.

Logs:

```
2022-06-13 19:30:16 DEBUG (MainThread) [glocaltokens.client] Initializing new GLocalAuthenticationTokens instance.
2022-06-13 19:30:16 DEBUG (MainThread) [glocaltokens.client] Set GLocalAuthenticationTokens client access_token, homegraph, access_token_date and homegraph_date to None
2022-06-13 19:30:16 DEBUG (MainThread) [glocaltokens.client] Set GLocalAuthenticationTokens client username to "m*****************************", password to "G*****************", master_token to "" and android_id to 
2022-06-13 19:30:16 DEBUG (SyncWorker_4) [glocaltokens.client] There is no stored master_token, logging in using username and password
2022-06-13 19:30:16 DEBUG (SyncWorker_4) [glocaltokens.client] There is no stored android_id, generating a new one
2022-06-13 19:30:16 DEBUG (SyncWorker_4) [glocaltokens.client] Generating android id...
2022-06-13 19:30:16 DEBUG (SyncWorker_4) [glocaltokens.client] Generated android id: b59e5184b7b029fd
2022-06-13 19:30:17 ERROR (SyncWorker_4) [glocaltokens.client] [!] Could not get master token.
2022-06-13 19:30:17 DEBUG (SyncWorker_4) [glocaltokens.client] Request response: {'Error': 'UNKNOWN_ERR'}
2022-06-13 19:30:17 ERROR (MainThread) [custom_components.google_home] 
```

manifest:

```json
{
  "after_dependencies": [
    "cloud",
    "http",
    "zeroconf"
  ],
  "codeowners": [
    "@leikoilja",
    "@DurgNomis-drol",
    "@ArnyminerZ",
    "@KapJI"
  ],
  "config_flow": true,
  "dependencies": [],
  "documentation": "https://github.com/leikoilja/ha-google-home",
  "domain": "google_home",
  "issue_tracker": "https://github.com/leikoilja/ha-google-home/issues",
  "name": "Google Home",
  "requirements": [
    "glocaltokens==0.6.4",
    "google-api-python-client==2.38.0"
  ],
  "version": "1.9.12",
  "zeroconf": [
    "_googlecast._tcp.local."
  ],
  "iot_class": "cloud_polling"
}
```

HA info:

```
Home Assistant Core 2022.6.5
Home Assistant Supervisor 2022.05.3
Home Assistant OS 8.1
```

Thoughts on the next debugging step?

**Comment by leikoilja** [comment]
@aaronpowell sorry to hear you are having issues. I suggest you try a simple python package https://github.com/leikoilja/glocaltokens that we use in this integration first in isolation. Try obtaining your master tokens. From the logs that you have posted, you are getting `UNKNOWN_ERR`, which is smth new... 
If the problem persists open a new issue ticket in glocaltokens repo :)

**Comment by aaronpowell** [comment]
> @aaronpowell sorry to hear you are having issues. I suggest you try a simple python package https://github.com/leikoilja/glocaltokens that we use in this integration first in isolation. Try obtaining your master tokens. From the logs that you have posted, you are getting `UNKNOWN_ERR`, which is smth new... If the problem persists open a new issue ticket in glocaltokens repo :)

Cool, will give that a go
