### ISSUE TITLE
Update 2024.11.0b0 Error

### ISSUE THREAD

**Issue by milandzuris** [leikoilja/ha-google-home#918]
## Logs

Logger: homeassistant.setup
Source: setup.py:269
First occurred: 20:49:05 (1 occurrences)
Last logged: 20:49:05

Setup failed for custom integration 'google_home': Requirements for google_home not found: ['glocaltokens==0.7.1'].

**Comment by schuettecarsten** [comment]
Can confirm this issue.

**Comment by milandzuris** [comment]
@leikoilja

**Comment by DnYDan** [comment]
yep, confirmed

**Comment by zacharee** [comment]
I was able to work around this by running `pip3 install glocaltokens==0.7.1 protobuf==4.25.5 grpcio-reflection==1.51.0 grpcio-status==1.51.0 async-timeout==4.0.3` in my Home Assistant Docker container and restarting Home Assistant.

My https://github.com/JohNan/home-assistant-flichub then failed, but reinstalling it and restarting fixed that.

**Comment by mesut3000** [comment]
I update 2024.11 and same error here.

**Comment by skgsergio** [comment]
The issue is that `ha-google-home` depends on `glocaltokens==0.7.1` which depends on `ghome-foyer-api==1.0.0` which, in the end, depends on `protobuf>=4.21.12,<5.0.0`.

However, HomeAssistant 2024.11 comes with `protobuf==5.28.3`, it was bumped to `5.x` in https://github.com/home-assistant/core/pull/124936 so a new version of `ghome-foyer-api` supporting `protobuf>=5` and a new version of `glocaltokens` is needed.

**Comment by satmandu** [comment]
Does someone want to open an issue at https://github.com/KapJI/ghome-foyer-api ?

**Comment by skgsergio** [comment]
I've tested with the code from https://github.com/KapJI/ghome-foyer-api/pull/124 and I've found yet another issue and is that now that `ghome-froyer-api` was updated for protobuf 5, the actual code is generated using `grpcio>=1.67.1` however Home Assistant uses `grpcio==1.66.2`:

```
ImportError: RuntimeError importing custom_components.google_home: The grpc package installed is at version 1.66.2, but the generated code in ghome_foyer_api/api_pb2_grpc.py depends on grpcio>=1.67.1. Please upgrade your grpc module to grpcio>=1.67.1 or downgrade your generated code using grpcio-tools<=1.66.2.
```

Maybe `glocaltokens` should have its own compatible with Home Assistant version of the generated protobuf code. It is a "big" change but probably the only reasonable way of keeping it in sync with HA versions.

**Comment by satmandu** [comment]
`ghome-foyer-api` hasn't had a release tagged yet.

Do you want to ask if `grpcio==1.66.2` can be used there?

**Comment by KapJI** [comment]
`ghome-foyer-api` v1.1.0 is published. I'd appreciate if someone can confirm that it solves the issue before we make a new release of this integration.

**Comment by sycx2** [comment]
Just installed it via pip and the error is resolved ;)

**Comment by KapJI** [comment]
v1.12.0 is released. Create new issue if something is still broken there.
